# Generated by Django 2.2.7 on 2019-11-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=10)),
                ('pmfdt', models.DateField()),
                ('pexpdt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='proxy',
            fields=[
            ],
            options={
                'ordering': ('pname',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inheritance_types.product',),
        ),
    ]
